start ::= item* EOF
item ::= declaration | ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )
declaration ::= file_decl | segment_decl | field_decl | dimension_decl | hierarchy_decl | define_decl | compute_decl | variable_decl | other_decl | ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )
file_decl ::= FILENAME_KW (EQUALS | COMMA)? ( STRING | ATTR | UNQUOTED_VALUE ) (COMMA ( ( ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) ) | ( STRING | ATTR | UNQUOTED_VALUE ) ))* COMMA? ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )?
segment_decl ::= SEGNAME_KW (EQUALS | COMMA)? ( STRING | ATTR | UNQUOTED_VALUE ) (COMMA ( ( ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) ) | ( STRING | ATTR | UNQUOTED_VALUE ) ))* COMMA? ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )?
field_decl ::= FIELDNAME_KW (EQUALS | COMMA)? ( STRING | ATTR | UNQUOTED_VALUE ) (COMMA ( ( ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) ) | ( STRING | ATTR | UNQUOTED_VALUE ) ))* COMMA? ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )?
dimension_decl ::= DIMENSION_KW (EQUALS | COMMA)? ( STRING | ATTR | UNQUOTED_VALUE ) (COMMA ( ( ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) ) | ( STRING | ATTR | UNQUOTED_VALUE ) ))* COMMA? ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )?
hierarchy_decl ::= HIERARCHY_KW (EQUALS | COMMA)? ( STRING | ATTR | UNQUOTED_VALUE ) (COMMA ( ( ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) ) | ( STRING | ATTR | UNQUOTED_VALUE ) ))* COMMA? ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )?
variable_decl ::= VARIABLE_KW (( ( ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) ) | ( STRING | ATTR | UNQUOTED_VALUE ) ) | COMMA)* ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )?
define_decl ::= DEFINE_KW ( ( STRING | ATTR | UNQUOTED_VALUE ) (SLASH ( STRING | ATTR | UNQUOTED_VALUE ))? ) EQUALS ( ATTR | UNQUOTED_VALUE | STRING | COMMA | EQUALS | SLASH | FILENAME_KW | SEGNAME_KW | FIELDNAME_KW | VARIABLE_KW | DEFINE_KW | COMPUTE_KW )+ SEMICOLON (COMMA ( ( ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) ) | ( STRING | ATTR | UNQUOTED_VALUE ) ))* COMMA? ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )?
compute_decl ::= COMPUTE_KW ( ( STRING | ATTR | UNQUOTED_VALUE ) (SLASH ( STRING | ATTR | UNQUOTED_VALUE ))? ) EQUALS ( ATTR | UNQUOTED_VALUE | STRING | COMMA | EQUALS | SLASH | FILENAME_KW | SEGNAME_KW | FIELDNAME_KW | VARIABLE_KW | DEFINE_KW | COMPUTE_KW )+ SEMICOLON (COMMA ( ( ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) ) | ( STRING | ATTR | UNQUOTED_VALUE ) ))* COMMA? ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )?
other_decl ::= ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) (COMMA ( ( ATTR EQUALS ( STRING | ATTR | UNQUOTED_VALUE ) ) | ( STRING | ATTR | UNQUOTED_VALUE ) ))* COMMA? ( '$' ANY_CHAR_EXCEPT_NL* (WS* '$' ANY_CHAR_EXCEPT_NL* )* )?
FILENAME_KW ::= 'FILENAME' | 'FILE'
SEGNAME_KW ::= 'SEGNAME' | 'SEGMENT'
FIELDNAME_KW ::= 'FIELDNAME' | 'FIELD'
DIMENSION_KW ::= 'DIMENSION'
HIERARCHY_KW ::= 'HIERARCHY'
VARIABLE_KW ::= 'VARIABLE'
DEFINE_KW ::= 'DEFINE'
COMPUTE_KW ::= 'COMPUTE'
COMMA ::= ','
EQUALS ::= '='
SLASH ::= '/'
SEMICOLON ::= ';'
ATTR ::= [a-zA-Z_] [a-zA-Z0-9_.]*
UNQUOTED_VALUE ::= [a-zA-Z0-9_./&%#@<>:*\-()+]+
STRING ::= '''' NOT ''''* '''' | '"' NOT '"'* '"'
WS ::= [ \t\r\n]+
ANY_CHAR_EXCEPT_NL ::= 'ANY_CHAR_EXCEPT_NL'
ANY_CHAR_EXCEPT_QUOTE ::= 'ANY_CHAR_EXCEPT_QUOTE'
ANY_CHAR_EXCEPT_DOUBLE_QUOTE ::= 'ANY_CHAR_EXCEPT_DOUBLE_QUOTE'
